### ISSUE TITLE
common comment service

### ISSUE THREAD

**Issue by rrgks6221** [modern-agile-team/dongurami-server-v2#104]
### Summary

create common comment service

### description

댓글에 대한 공통 로직을 수행하는 CommonCommentService 를 생성합니다.

### To-Do

- [ ] comment soft delete 를 위한 migrations
- [ ] CommonCommentsService 생성
  - [ ] 댓글 생성
  - [ ] 댓글 전체조회
  - [ ] 댓글 상세조회
  - [ ] 댓글 put 수정
  - [ ] 댓글 삭제
- [ ] CommonReplyCommentsService
  - [ ] 대댓글 생성
  - [ ] 대댓글 전체조회
  - [ ] 대댓글 상세조회
  - [ ] 대댓글 put 수정
  - [ ] 대댓글 삭제

**Comment by rrgks6221** [comment]
통합이 불가능할거같아서 close 하고 자유게시글에대한 댓글, 대댓글로 새로 만들겠습니다.
