### ISSUE TITLE
create notice board entity

### ISSUE THREAD

**Issue by hobiJeong** [modern-agile-team/dongurami-server-v2#23]
### Summary
공지 게시판 Entity를 생성합니다.

### description
migration을 통해 테이블을 생성합니다.

### To-Do

- [x] 공지 게시판 Table
- [x] 공지 게시판 댓글 Table
- [x] 공지 게시판 대댓글 Table
- [x] 공지 게시판 반응 Table
- [x] 공지 게시판 댓글 반응 Table
- [x] 공지 게시판 대댓글 반응 Table
