### ISSUE TITLE
success interceptor

### ISSUE THREAD

**Issue by rrgks6221** [modern-agile-team/dongurami-server-v2#35]
### Summary

create and apply success interceptor

### description

- 성공 시 응답값 통일을 위해 전역 success interceptor 를 생성
  - apply user endpoint
  - apply auth endpoint

### To-Do

- [x] global success interceptor 생성
  - [x] apply user endpoint
  - [x] apply auth endpoint
