### ISSUE TITLE
unused code

### ISSUE THREAD

**Issue by rrgks6221** [modern-agile-team/dongurami-server-v2#38]
### Summary

사용하지 않는 코드를 삭제합니다.

### description

사용하지 않는 코드를 삭제합니다.

### To-Do

- [x] apis 내부 module 들
- [x] common 내부 코드
- [x] src/config
- [x] output
- [x] AppController, AppService
- [x] .gitignore 로 .vscode 제거
