### ISSUE TITLE
free board history entity

### ISSUE THREAD

**Issue by rrgks6221** [modern-agile-team/dongurami-server-v2#53]
### Summary

자유게시판 history entity

### description

데이터 히스토리를 쌓기 위해 자유게시판 history 테이블을 생성하는 migration 을 생성합니다.

### To-Do

- [x] free_board_history table
- [x] free_board_comment_history table
- [x] free_board_reply_comment_history table
