### ISSUE TITLE
match majorCategory

### ISSUE THREAD

**Issue by hobiJeong** [modern-agile-team/dongurami-server-v2#59]
### Summary
학과 전공 명이랑 코드를 매칭 시켜서 로우에 집어넣기 및 api 생성

### description
migration을 통해 학과 전공 명이랑 코드를 매칭 시켜서 로우에 집어넣기(기존에 있던 로우 삭제)
학과코드를 생성해서 로우에 추가할 수 있는 api 생성
swagger문서 생성(ApiProperty 정도만)

### To-Do

- [x] migration을 통해 학과 전공 명이랑 코드를 매칭 시켜서 로우에 집어넣기(기존에 있던 로우 삭제)
- [x] 학과코드를 생성해서 로우에 추가할 수 있는 api 생성
- [x] swagger문서 생성(ApiProperty 정도만)
