### ISSUE TITLE
free board soft delete

### ISSUE THREAD

**Issue by rrgks6221** [modern-agile-team/dongurami-server-v2#80]
### Summary

free board soft delete

### description

free board 를 soft delete 하게끔 변경합니다.

### To-Do

- [x] free board migration
- [x] free board history migration
- [x] free board crud 변경

### Related Issue Link

#61
