### ISSUE TITLE
free board is anonymous

### ISSUE THREAD

**Issue by rrgks6221** [modern-agile-team/dongurami-server-v2#82]
### Summary

free board is anonymous

### description

자유게시글 익명여부 DB table camel case 에서 snake case 로 변경

### To-Do

- [x] free_board
- [x] free_board_history
- [x] free_board_comment
- [x] free_board_comment_history
- [x] free_board_reply_comment
- [x] free_board_reply_comment_history
